# Generated by Django 4.1 on 2024-05-18 11:42

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("new", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[config.validators.PhoneValidator()],
                        verbose_name="موبایل",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="زمان ثبت نام"
                    ),
                ),
            ],
            options={
                "verbose_name": "عضو خبرنامه",
                "verbose_name_plural": "اعضاء خبرنامه",
            },
        ),
    ]
