# Generated by Django 4.1 on 2024-06-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("new", "0002_newslettermember"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_suggest",
                    models.BooleanField(
                        default=True, verbose_name="آیا پیشنهاد میکنم ؟"
                    ),
                ),
                ("content", models.TextField(verbose_name="متن")),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=225, null=True, verbose_name="نام کامل"
                    ),
                ),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
            ],
            options={
                "verbose_name": "نظر مشتری",
                "verbose_name_plural": "نظرات مشتریان",
            },
        ),
    ]
