# Generated by Django 4.1 on 2024-05-13 19:47

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery",
            options={"verbose_name": "گالری", "verbose_name_plural": "گالری"},
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(
                upload_to=gallery.models.gallery_image_file_path, verbose_name="تصویر"
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="title",
            field=models.CharField(
                blank=True, max_length=125, null=True, verbose_name="عنوان"
            ),
        ),
    ]
