# Generated by Django 4.1 on 2024-05-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_alter_gallery_options_alter_gallery_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="is_show",
            field=models.BooleanField(default=False, verbose_name="قابل نمایش در سایت"),
        ),
    ]
