# Generated by Django 4.1 on 2024-06-27 22:31

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0003_gallery_is_show"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=125, null=True, verbose_name="عنوان"
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        upload_to=gallery.models.medial_video_file_path,
                        verbose_name="فایل",
                    ),
                ),
            ],
            options={
                "verbose_name": "مدیا",
                "verbose_name_plural": "مدیا",
            },
        ),
    ]
