# Generated by Django 4.1 on 2024-06-27 23:01

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0004_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="file",
            field=models.FileField(
                upload_to=gallery.models.medial_video_file_path, verbose_name="فایل"
            ),
        ),
    ]
