# Generated by Django 4.1 on 2024-09-15 09:38

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0005_alter_media_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="is_show",
            field=models.BooleanField(default=False, verbose_name="قابل نمایش در سایت"),
        ),
        migrations.AddField(
            model_name="media",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=gallery.models.gallery_image_file_path,
                verbose_name="تصویر",
            ),
        ),
    ]
