# Generated by Django 4.1 on 2024-05-18 09:12

import config.validators
import cooperation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CooperationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125, verbose_name="نوع همکاری")),
            ],
            options={
                "verbose_name": "نوع همکاری",
                "verbose_name_plural": "انواع همکاری",
            },
        ),
        migrations.CreateModel(
            name="CooperationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=125, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=125, verbose_name="نام خانوادگی"),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=11,
                        validators=[config.validators.PhoneValidator()],
                        verbose_name="شماره موبایل",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=125, verbose_name="پست الکترونیک"),
                ),
                (
                    "cv",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=cooperation.models.cv_file_path,
                        verbose_name="رزومه",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, max_length=1200, null=True, verbose_name="پیام"
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ارسال"),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cooperation.cooperationtype",
                        verbose_name="نوع همکاری",
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست همکاری",
                "verbose_name_plural": "درخواست های همکاری",
            },
        ),
    ]
