# Generated by Django 4.1 on 2024-05-16 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gallery", "0002_alter_gallery_options_alter_gallery_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUsExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_title",
                    models.CharField(max_length=72, verbose_name="عنوان اصلی"),
                ),
                ("title", models.CharField(max_length=125, verbose_name="عنوان")),
            ],
            options={
                "verbose_name": "افزونه درباره ما",
                "verbose_name_plural": "افزونه های درباره ما",
            },
        ),
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125, verbose_name="عنوان")),
                ("text", models.TextField(blank=True, null=True, verbose_name="متن")),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="about_image",
                        to="gallery.gallery",
                        verbose_name="تصویر",
                    ),
                ),
            ],
            options={
                "verbose_name": "درباره ما",
                "verbose_name_plural": "درباره ما",
            },
        ),
    ]
