# Generated by Django 4.1 on 2024-05-16 23:31

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=225, null=True, verbose_name="عنوان"
                    ),
                ),
            ],
            options={
                "verbose_name": "آدرس",
                "verbose_name_plural": "آدرس ها",
            },
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=125, verbose_name="پست الکترونیک"),
                ),
            ],
            options={
                "verbose_name": "پست الکترونیک",
                "verbose_name_plural": "پست های الکترونیک",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=125, verbose_name="نام کامل"),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=11,
                        validators=[config.validators.PhoneValidator()],
                        verbose_name="شماره موبایل",
                    ),
                ),
                ("text", models.CharField(max_length=1200, verbose_name="متن پیام")),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ارسال"),
                ),
            ],
            options={
                "verbose_name": "درخواست",
                "verbose_name_plural": "درخواست ها",
            },
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=21, verbose_name="شماره تماس")),
            ],
            options={
                "verbose_name": "شماره تماس",
                "verbose_name_plural": "شماره های تماس",
            },
        ),
    ]
