# Generated by Django 4.1 on 2024-05-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contactus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address",
            field=models.CharField(
                blank=True, max_length=225, null=True, verbose_name="آدرس"
            ),
        ),
    ]
