# Generated by Django 4.1 on 2024-05-18 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
            ],
            options={
                "verbose_name": "نمایندگی",
                "verbose_name_plural": "نمایندگی ها",
            },
        ),
        migrations.CreateModel(
            name="Agent_Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125, verbose_name="نام شعبه")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=225, null=True, verbose_name="آدرس"
                    ),
                ),
                (
                    "phones",
                    models.CharField(
                        blank=True, max_length=225, null=True, verbose_name="شماره تماس"
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="agent.agent",
                        verbose_name="نمایندگی",
                    ),
                ),
            ],
            options={
                "verbose_name": "شعبه نمایندگی",
                "verbose_name_plural": "شعبه های نمایندگی",
            },
        ),
    ]
