# Generated by Django 4.1 on 2024-05-18 08:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gallery", "0002_alter_gallery_options_alter_gallery_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125, verbose_name="عنوان")),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_feature_logo",
                        to="gallery.gallery",
                        verbose_name="تصویر",
                    ),
                ),
            ],
            options={
                "verbose_name": "امکانات",
                "verbose_name_plural": "امکانات",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="عنوان")),
                (
                    "desc",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="توضیحات"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=project.models.project_image_file_path,
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "features",
                    models.ManyToManyField(
                        related_name="projects",
                        to="project.feature",
                        verbose_name="امکانات",
                    ),
                ),
                (
                    "gallery",
                    models.ManyToManyField(
                        related_name="projects",
                        to="gallery.gallery",
                        verbose_name="گالری",
                    ),
                ),
            ],
            options={
                "verbose_name": "پروژه",
                "verbose_name_plural": "پروژه ها",
            },
        ),
        migrations.CreateModel(
            name="Project_Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=125, verbose_name="مشخصه")),
                ("value", models.CharField(max_length=225, verbose_name="مقدار")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="project.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشخصه پروژه",
                "verbose_name_plural": "مشخصات پروژه ها",
            },
        ),
        migrations.CreateModel(
            name="Project_Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=225, verbose_name="مقدار")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="props",
                        to="project.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویژگی پروژه",
                "verbose_name_plural": "ویژگی پروژه ها",
            },
        ),
    ]
