# Generated by Django 4.1 on 2024-06-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0004_media"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="media",
            field=models.ManyToManyField(
                related_name="projects", to="gallery.media", verbose_name="مدیا"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[("P", "پروژهای در حال انجام"), ("D", "پروژهای انجام شده")],
                default="P",
                max_length=2,
            ),
        ),
    ]
