# Generated by Django 4.1 on 2024-06-28 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_project_google_map_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125, verbose_name="نام")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "بلوک",
                "verbose_name_plural": "بلوک ها",
            },
        ),
        migrations.CreateModel(
            name="Block_Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=125, verbose_name="مشخصه")),
                ("value", models.CharField(max_length=225, verbose_name="مقدار")),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="project.block",
                        verbose_name="بلوک",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشخصه بلوک",
                "verbose_name_plural": "مشخصات بلوک ها",
            },
        ),
    ]
