# Generated by Django 4.1 on 2024-06-28 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_block_block_specification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks",
                to="project.project",
                verbose_name="پروژه",
            ),
        ),
    ]
