# Generated by Django 4.1 on 2024-06-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_project_view_3d"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="google_map_url",
            field=models.URLField(
                blank=True,
                error_messages={"invalid": "مقدار وارد شده صحیح نم باشد"},
                max_length=500,
                null=True,
                verbose_name="لینک گوگل مپ",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="view_3d",
            field=models.URLField(
                blank=True,
                error_messages={"invalid": "مقدار وارد شده صحیح نم باشد"},
                max_length=500,
                null=True,
                verbose_name="لینک نمای ۳ بعدی",
            ),
        ),
    ]
