# Generated by Django 4.1 on 2024-07-04 06:37

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0005_alter_media_file"),
        ("project", "0008_block_child_csv_file_block_main_csv_data_mainchart_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="block",
            old_name="main_csv_data",
            new_name="type_csv_file",
        ),
        migrations.RemoveField(
            model_name="mainchart",
            name="block",
        ),
        migrations.AddField(
            model_name="block",
            name="main_csv_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=project.models.csv_file_path,
                verbose_name="فایل csv دوم",
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="child_csv_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=project.models.csv_file_path,
                verbose_name="فایل csv سوم",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="features",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="projects",
                to="project.feature",
                verbose_name="امکانات",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="gallery",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="projects",
                to="gallery.gallery",
                verbose_name="گالری",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="media",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="projects",
                to="gallery.media",
                verbose_name="مدیا",
            ),
        ),
        migrations.CreateModel(
            name="ChartType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveBigIntegerField(verbose_name="شناسه")),
                ("label", models.CharField(max_length=125, verbose_name="عنوان")),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charts",
                        to="project.block",
                        verbose_name="بلوک",
                    ),
                ),
            ],
            options={
                "verbose_name": "نمودار",
                "verbose_name_plural": "نمودارها",
            },
        ),
        migrations.AddField(
            model_name="mainchart",
            name="type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charts",
                to="project.charttype",
                verbose_name="نمودار",
            ),
            preserve_default=False,
        ),
    ]
