# Generated by Django 4.1 on 2024-07-04 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0010_alter_mainchart_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainchart",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charts",
                to="project.charttype",
                verbose_name="نمودار",
            ),
        ),
    ]
