# Generated by Django 4.1 on 2024-05-16 23:31

import config.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gallery", "0002_alter_gallery_options_alter_gallery_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=72, null=True, verbose_name="عنوان"
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        error_messages={"invalid": "مقدار وارد شده صحیح نم باشد"},
                        max_length=500,
                        null=True,
                        verbose_name="لینک",
                    ),
                ),
                (
                    "footer_link_type",
                    models.CharField(
                        choices=[("F", "لینک سریع"), ("C", "تماس با ما")],
                        default="F",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "لینک فوتر",
                "verbose_name_plural": "لینک های فوتر",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=125, null=True, verbose_name="عنوان"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="توضیحات"
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_logo",
                        to="gallery.gallery",
                        verbose_name="لوگو",
                    ),
                ),
            ],
            options={
                "verbose_name": "خدمت",
                "verbose_name_plural": "خدمات",
            },
        ),
        migrations.CreateModel(
            name="HomeHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo_title",
                    models.CharField(
                        blank=True, max_length=72, null=True, verbose_name="عنوان"
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        blank=True, max_length=125, null=True, verbose_name="سر تیتر"
                    ),
                ),
                (
                    "heading2",
                    models.CharField(
                        blank=True, max_length=125, null=True, verbose_name="2 سر تیتر"
                    ),
                ),
                (
                    "paragraph",
                    models.CharField(
                        blank=True, max_length=700, null=True, verbose_name="پاراگرف"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=21,
                        null=True,
                        validators=[config.validators.PhoneValidator()],
                        verbose_name="شماره موبایل",
                    ),
                ),
                (
                    "heading_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="heading",
                        to="gallery.gallery",
                        verbose_name="تصویر تیتر",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logo",
                        to="gallery.gallery",
                        verbose_name="لوگو",
                    ),
                ),
            ],
            options={
                "verbose_name": "تیتر صفحه اصلی",
                "verbose_name_plural": "تیتر صفحه اصلی",
            },
        ),
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=72, null=True, verbose_name="عنوان"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=1500, null=True, verbose_name="توضیحات"
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="footer_logo",
                        to="gallery.gallery",
                        verbose_name="لوگو",
                    ),
                ),
            ],
            options={
                "verbose_name": "فوتر",
                "verbose_name_plural": "فوتر",
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=125, null=True, verbose_name="عنوان"
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feature_logo",
                        to="gallery.gallery",
                        verbose_name="تصویر",
                    ),
                ),
            ],
            options={
                "verbose_name": "امکان",
                "verbose_name_plural": "امکانات",
            },
        ),
        migrations.CreateModel(
            name="Communication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=72, null=True, verbose_name="عنوان"
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        error_messages={"invalid": "مقدار وارد شده صحیح نم باشد"},
                        max_length=500,
                        null=True,
                        verbose_name="لینک",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="communication_logo",
                        to="gallery.gallery",
                        verbose_name="لوگو",
                    ),
                ),
            ],
            options={
                "verbose_name": "راه ارتباطی",
                "verbose_name_plural": "راه های ارتباطی",
            },
        ),
    ]
