# Generated by Django 4.1 on 2024-05-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siteinfo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footerlink",
            name="footer_link_type",
            field=models.CharField(
                choices=[("F", "لینک سریع"), ("C", "تماس با ما")],
                default="F",
                max_length=1,
                verbose_name="نوع لینک",
            ),
        ),
    ]
