# Generated by Django 4.1 on 2024-06-28 12:47

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siteinfo", "0003_homeheader_media_homeheader_middle_heading_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Critic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=125, verbose_name="نام کامل"),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=11,
                        validators=[config.validators.PhoneValidator()],
                        verbose_name="شماره موبایل",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=125, verbose_name="پست الکترونیک"),
                ),
                ("text", models.CharField(max_length=1200, verbose_name="متن پیام")),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ارسال"),
                ),
            ],
            options={
                "verbose_name": "انتقاد و پیشنهاد",
                "verbose_name_plural": "انتقادات و پیشنهادات",
            },
        ),
    ]
